### ISSUE TITLE
assignment_group at ServiceNow

### ISSUE THREAD

**Issue by maniasso** [SNapier/NagiosXI-ServiceNow-EventHandler#5]
hello, is there a way to inform the assignment_group? I don't see option for this at the script, how the script handles which group would have the ticket assigned?
Thank you

**Comment by SNapier** [comment]
@maniasso currently in the script there is no provision for passing the ServiceNow assignment group as part of the payload being sent to the service Now incidents table OOB.
One possible solution would be using NagiosXI "Free Variables" for either the host or service in which the handler is assigned and extending the event handler implementation to pass the key:value pair.

NagiosXI Docs
https://assets.nagios.com/downloads/nagiosxi/docs/Understanding-Nagios-XI-Notification-Variables.pdf

Feel free to open feature request.
--SN
